package net.dark_roleplay.core_modules.maarg;

import java.io.File;
import java.util.Arrays;
import java.util.List;

import net.dark_roleplay.library.resources.ModDataFolders;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;

public class References {
	public static final String MODID = "drpcmmaarg";
	public static final String NAME = "Dark Roleplay Core Module - Materials and Automatic Resource Generation";
	public static final String VERSION = "1.12.2-0.10.0-SNAPSHOT";
	public static final String ACCEPTEDVERSIONS = "[1.12.2,)";
	public static final String UPDATE_JSON = "https://dark-roleplay.net/files/versions/core_modules/drpcmmaarg/drpcmmaarg-1.12.2.json";
	public static final String DEPENDECIES = "required-after:forge@[1.12.2-14.23.4.2705,);required-after:drplibrary@[1.12.2-0.1.1.4,)";
	public static final String URL = "http://dark-roleplay.net/";
	public static final List<String> AUTHORS = Arrays.asList("JTK222");
	public static final String CREDITS = "Lead Programmer: JTK222";
	public static final String DESCRIPTION = "Dark Roleplay Core Modules are included into Dark Roleplay Core, they are used for easier modulation and updaing.";

	public static File FOLDER_MAIN;
	public static File FOLDER_LOGS;
	public static File FOLDER_ARG;
	public static File FOLDER_ARG_DATA;


	@Mod.Metadata(value = References.MODID, owner = References.MODID)
	public static ModMetadata MOD_META = null;

	public static void init(FMLPreInitializationEvent event){

		MOD_META.autogenerated = false;
		MOD_META.modId = MODID;
		MOD_META.name = NAME;
		MOD_META.authorList = AUTHORS;
		MOD_META.credits = CREDITS;
		MOD_META.description = DESCRIPTION;
		MOD_META.version = VERSION;
		MOD_META.url = URL;
		MOD_META.updateJSON = UPDATE_JSON;
		MOD_META.parent = "drpcore";

		FOLDER_MAIN = new File(event.getModConfigurationDirectory().getParentFile().getPath() + "/dark roleplay/");

		if(ModDataFolders.doesGlobalModDataExist()) {
			FOLDER_MAIN = ModDataFolders.getModDataFolder("Dark Roleplay/Modules/MaARG/");
		}
		FOLDER_MAIN.mkdirs();

		FOLDER_LOGS = new File(FOLDER_MAIN, "logs");
		FOLDER_LOGS.mkdirs();

		FOLDER_ARG = new File(FOLDER_MAIN, "/resources/assets/");
		FOLDER_ARG.mkdirs();

		FOLDER_ARG_DATA = new File(FOLDER_MAIN, "/resources/data/");
		FOLDER_ARG_DATA.mkdirs();
	}
}